[Model]
architecture = "pythae_VAE"

[Architecture]
first_layer_channels = 32
n_conv_encoder = 5
feature_size = 0
latent_space_size = 256
n_conv_decoder = 5
last_layer_channels = 32
last_layer_conv = false

[Pythae]

[Computational]
gpu = true
n_proc = 10
batch_size = 8

[Data]
diagnoses = ["CN"]

[Cross_validation]
n_splits = 6
split = [0]

[Optimization]
epochs = 200
learning_rate = 1e-5